openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: https://nodemanten.heningimam.com
    description: Nodemanten

paths:
  /wish:
    post:
      summary: Post a wish
      # description: Post a wish
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string  
    # get:
    #   summary: Returns a list of users.
    #   description: Optional extended description in CommonMark or HTML.
    #   responses:
    #     '200':    # status code
    #       description: A JSON array of user names
    #       content:
    #         application/json:
    #           schema: 
    #             type: array
    #             items: 
    #               type: string